[species]
inv = [
    "CO2",
    "H2O",
    "NOx",
    "distance",
]
nox = "NO2"
out = [
    "CO2",
    "H2O",
    "O3",
    "CH4",
    "PMO",
    "cont",
    "SWV",
]

[inventories]
dir = "C:/Users/atzeh/PycharmProjects/OAC_Thesis/ATZE/"
files = [
    "emi_inv_2020_DEPA.nc",
]
rel_to_base = false

[inventories.base]
dir = "input/"
files = [
    "rnd_inv_2020.nc",
    "rnd_inv_2030.nc",
    "rnd_inv_2040.nc",
    "rnd_inv_2050.nc",
]

[output]
full_run = true
dir = "results_GBAU_SSP1-1_9/"
name = "GBAU_SSP1-1_9"
overwrite = true
concentrations = false

[time]
dir = ""
range = [
    1940,
    2101,
    1,
]
file = "evolution/GBAU_evo.nc"

[background]
dir = "../../repository/"

[background.CO2]
file = "co2_bg.nc"
scenario = "SSP1-1.9"

[background.CH4]
file = "ch4_bg.nc"
scenario = "SSP1-1.9"

[background.N2O]
file = "n2o_bg.nc"
scenario = "SSP1-1.9"

[responses]
dir = "../../repository/"

[responses.CO2]
response_grid = "0D"

[responses.CO2.conc]
method = "Sausen&Schumann"

[responses.H2O]
response_grid = "2D"

[responses.H2O.rf]
file = "resp_RF.nc"

[responses.O3]
response_grid = "2D"

[responses.O3.rf]
file = "resp_RF_O3.nc"

[responses.CH4]
response_grid = "2D"

[responses.CH4.tau]
file = "resp_ch4.nc"

[responses.CH4.rf]
method = "Etminan_2016"

[responses.cont]
response_grid = "cont"

[responses.cont.resp]
file = "resp_cont_lf.nc"

[temperature]
method = "Boucher&Reddy"

[temperature.CO2]
lambda = 0.73

[temperature.H2O]
efficacy = 1.14

[temperature.O3]
efficacy = 1.37

[temperature.PMO]
efficacy = 1.37

[temperature.CH4]
efficacy = 1.14

[temperature.cont]
efficacy = 0.59

[temperature.SWV]
efficacy = 1.14

[metrics]
types = [
    "AGWP",
    "ATR",
    "AGTP",
]
H = [
    20,
    100,
]
t_0 = [
    2000,
    2001,
    2002,
    2003,
    2004,
    2005,
    2006,
    2007,
    2008,
    2009,
    2010,
    2011,
    2012,
    2013,
    2014,
    2015,
    2016,
    2017,
    2018,
    2019,
    2020,
    2021,
    2022,
    2023,
    2024,
    2025,
    2026,
    2027,
    2028,
    2029,
    2030,
    2031,
    2032,
    2033,
    2034,
    2035,
    2036,
    2037,
    2038,
    2039,
    2040,
    2041,
    2042,
    2043,
    2044,
    2045,
    2046,
    2047,
    2048,
    2049,
    2050,
    2051,
    2052,
    2053,
    2054,
    2055,
    2056,
    2057,
    2058,
    2059,
    2060,
    2061,
    2062,
    2063,
    2064,
    2065,
    2066,
    2067,
    2068,
    2069,
    2070,
    2071,
    2072,
    2073,
    2074,
    2075,
    2076,
    2077,
    2078,
    2079,
    2080,
    2081,
    2082,
    2083,
    2084,
    2085,
    2086,
    2087,
    2088,
    2089,
    2090,
    2091,
    2092,
    2093,
    2094,
    2095,
    2096,
    2097,
    2098,
    2099,
    2100,
]

[aircraft]
types = [
    "DEFAULT",
]

[aircraft.DEFAULT]
G_250 = 1.7
eff_fac = 1.0
PMrel = 1.0
