# This is a configuration file for demonstrating OpenAirClim

# Species considered
[species]
# Species defined in emission inventories
# possible values: "CO2", "H2O", "NOx", "distance"
inv = ["CO2", "H2O", "NOx", "distance"]
# Assumed NOx species in emission inventory
# possible values: "NO", "NO2"
nox = "NO2"
# Output / response species
# possible values: "CO2", "H2O", "O3", "CH4", "PMO", "cont", TODO "SWV" is added here, it should only be possible if CH4 is also there
out = ["CO2", "H2O", "O3", "CH4", "PMO", "cont", "SWV"]

# Emission inventories                                                    
[inventories]
dir = "C:/Users/atzeh/PycharmProjects/OAC_Thesis/ATZE/"
files = [
    "emi_inv_2020_DEPA.nc", # Check
#    "emi_inv_2025_DEPA.nc",
#    "emi_inv_2030_DEPA.nc",
#    "emi_inv_2035_DEPA.nc",
#    "emi_inv_2040_DEPA.nc",
#    "emi_inv_2045_DEPA.nc",
#    "emi_inv_2050_DEPA.nc",
    #    "rnd_inv_2050.nc",
    #    "rnd_inv_2060.nc",
    #    "rnd_inv_2070.nc",
    #    "rnd_inv_2080.nc",
    #    "rnd_inv_2090.nc",
    #    "rnd_inv_2100.nc",
    #    "rnd_inv_2110.nc",
    #    "rnd_inv_2120.nc",
]
# base emission inventories, only considered if rel_to_base = true
rel_to_base = false
base.dir = "input/"
base.files = [
    "rnd_inv_2020.nc",
    "rnd_inv_2030.nc",
    "rnd_inv_2040.nc",
    "rnd_inv_2050.nc",
]

# Output options
[output]
# Full simulation run = true, climate metrics only = false
full_run = true
dir = "results_GFP2050/"
name = "GFP2050" #Check
overwrite = true
# Computation of 2D concentration responses is not yet supported.
# possible values: false 
concentrations = false

# Time settings
[time]
dir = ""
# Time range in years: t_start, t_end, step, (t_end not included)
range = [1940, 2101, 1]
# Time evolution of emissions
# either type "scaling" or type "norm"
#file = "time_scaling_2percentgrowthperyear.nc"  # TODO Applying this scaling cause the sin patern to exist, but no extrapolation
file = "evolution/GFP2050_evo.nc" # Check

# Global background concentrations
[background]
dir = "../../repository/"
CO2.file = "co2_bg.nc"
CO2.scenario = "SSP2-4.5"
#CO2.scenario = "SSP1-1.9"
#CO2.scenario = "SSP4-6.0"
#CO2.scenario = "SSP3-7.0"
CH4.file = "ch4_bg.nc"
CH4.scenario = "SSP2-4.5" # check SSP scenario
N2O.file = "n2o_bg.nc"
N2O.scenario = "SSP2-4.5"

# Response options
[responses]
dir = "../../repository/"
CO2.response_grid = "0D"
CO2.conc.method = "Sausen&Schumann"
# RF method based on Etminan et al. 2016 is used by default.
#CO2.rf.method = "Etminan_2016"

H2O.response_grid = "2D"
H2O.rf.file = "resp_RF.nc"    # AirClim response surface

O3.response_grid = "2D"
O3.rf.file = "resp_RF_O3.nc"  # tagging
#O3.rf.file = "resp_RF.nc"    # AirClim response surface, requires adjustment of CORR_RF_O3 !

CH4.response_grid = "2D"
CH4.tau.file = "resp_ch4.nc"  # tagging
CH4.rf.method = "Etminan_2016"

cont.response_grid = "cont"
cont.resp.file = "resp_cont_lf.nc"

# Temperature options
[temperature]
# valid methods: "Boucher&Reddy"
method = "Boucher&Reddy"
# Climate sensitivity parameter, Ponater et al. 2006, Table 1
# https://doi.org/10.1016/j.atmosenv.2006.06.036
CO2.lambda = 0.73
# Efficacies, Ponater et al. 2006, Table 1
H2O.efficacy = 1.14
O3.efficacy = 1.37
PMO.efficacy = 1.37
CH4.efficacy = 1.14
cont.efficacy = 0.59
SWV.efficacy = 1.14 # TODO This is taken from the source, as SWV is H2O

# Climate metrics options
[metrics]
# iterate over elements in lists types t_0 and H
types = ["AGWP", "ATR", "AGTP"] # valid climate metrics: AGTP, AGWP, ATR # TODO Check what metric i want
H = [20,100]                        # Time horizon, t_final = t_0 + H - 1
t_0 = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032,
       2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043,
       2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054,
       2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065,
       2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076,
       2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087,
       2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098,
       2099, 2100]                   # Start time for metrics calculation

# aircraft defined in inventory
# following identifiers are NOT allowed: "TOTAL"
# "DEFAULT" is used if "ac" coordinate not defined in emission inventories
# G_250, eff_fac and PMrel must be defined for each aircraft if contrails are
# to be calculated.
[aircraft]
types = ["DEFAULT"]
DEFAULT.G_250 = 1.70   # Schmidt-Appleman mixing line slope at 250 hPa
DEFAULT.eff_fac = 1.0  # efficiency factor compared to 0.333
DEFAULT.PMrel = 1.0    # relative PM emissions compared to 1e15
